-- ============================================================================
-- Migration 009 — Human-readable reference number (P2-1)
-- Run once in Supabase SQL Editor. Idempotent.
-- ============================================================================
--
-- `items.ref` is a short sequential number a student can say out loud
-- ("c'est le 142"), type into search, and quote in a claim message to tell two
-- black phones apart. It is not a URL — there is no item detail route.
--
-- Backfilled in created_at order so the numbering reflects real history: the
-- oldest post is #0001. Adding an identity column without an explicit backfill
-- would number rows in physical heap order, which is arbitrary and would
-- permanently mislabel the board.
-- ============================================================================


-- ── 1. Column ────────────────────────────────────────────────────────────────

ALTER TABLE public.items ADD COLUMN IF NOT EXISTS ref bigint;


-- ── 2. Backfill in created_at order ──────────────────────────────────────────
-- id breaks ties: six rows share a synthetic 12:00:00 timestamp from the
-- original data import, and row_number() must be deterministic across re-runs.

WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
  FROM public.items
)
UPDATE public.items i
SET ref = o.rn
FROM ordered o
WHERE i.id = o.id
  AND i.ref IS NULL;

ALTER TABLE public.items ALTER COLUMN ref SET NOT NULL;


-- ── 3. Make it an identity column, continuing after the backfill ─────────────
-- Guarded: ALTER ... ADD GENERATED raises if the column is already an identity,
-- which would make a second run of this file fail.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.items'::regclass
      AND attname = 'ref'
      AND attidentity <> ''
  ) THEN
    ALTER TABLE public.items ALTER COLUMN ref ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Start the sequence after the highest backfilled value, or at 1 on an empty
-- table. is_called = false means the next nextval() returns exactly this value.
SELECT setval(
  pg_get_serial_sequence('public.items', 'ref'),
  COALESCE((SELECT max(ref) FROM public.items), 0) + 1,
  false
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_items_ref ON public.items (ref);


-- ── 4. Grant — REQUIRED, and easy to miss ────────────────────────────────────
-- Migration 004 revoked the table-level SELECT grant on items and re-granted
-- readable columns individually. A new column is therefore invisible to every
-- client until it is granted explicitly, and the failure looks like the column
-- silently not existing rather than a permission error.

GRANT SELECT (ref) ON public.items TO authenticated;


-- ── 5. Ledger ────────────────────────────────────────────────────────────────

INSERT INTO public.schema_migrations (filename)
VALUES ('009-item-ref.sql')
ON CONFLICT (filename) DO NOTHING;


-- Verify — expect a gapless 1..N ordered by created_at:
--
--   SELECT ref, created_at FROM public.items ORDER BY ref LIMIT 10;
--   SELECT count(*), count(DISTINCT ref), min(ref), max(ref) FROM public.items;
