-- ============================================================================
-- Migration 013 — Lock the client-supplied insert columns
-- Run once in Supabase SQL Editor. Idempotent.
-- ============================================================================
--
-- Migration 012 closed status against UPDATE. It said nothing about INSERT, and
-- INSERT is where the rest of the row is decided. Today a signed-in student can
-- do all of this from a browser console:
--
--   await supabase.from('items').insert({
--     type: 'found', category: 'other', location: 'library', date: '2026-01-01',
--     user_id: <their own uid>,          -- RLS requires this to be theirs
--     user_email: 'someone.else@estin.dz',   -- not checked
--     user_name:  'Someone Else',            -- not checked
--     status:     'claimed',                 -- not checked
--     created_at: '2020-01-01',              -- not checked
--     ref:        999999                     -- not checked
--   })
--
-- RLS pins user_id and nothing else. The denormalised identity columns, the
-- status the board renders from, the timestamp the 90-day expiry reads, and the
-- human-readable reference are all whatever the client says they are.
--
-- Two independent layers here, deliberately:
--   1. A BEFORE INSERT trigger stamps the trustworthy values, so a row is
--      correct even if some future grant is loosened by accident.
--   2. Column-level INSERT grants, so a client that tries anyway gets 42501
--      rather than being silently overwritten.
--
-- ############################################################################
-- PAIRED CHANGE — THIS FILE AND ITS CLIENT COMMIT ARE ONLY CORRECT TOGETHER.
--
-- Partner commit: "fix: stop sending server-stamped columns on item insert",
-- which removes user_email, user_name and status from the insert payload in
-- src/components/report/report-form.tsx.
--
-- Applying this migration WITHOUT that client change:
--   The form still sends user_email, user_name and status. Section 4 makes
--   those columns uninsertable by `authenticated`, so every student post fails
--   with 42501 "permission denied for column user_email". Posting is dead.
--
-- Deploying that client change WITHOUT this migration:
--   No stamping trigger exists yet, so user_email and user_name land NULL on
--   every new row. claim_item() returns poster_email from that column, so a
--   student who claims an item gets no contact details back — the reunion flow
--   silently stops working, and nothing errors.
--
-- Neither failure is loud. Ship them in the same release, in this order:
-- apply the migration, then deploy the client.
-- ############################################################################
--
-- Scope note: this is pre-existing behaviour from ff80fda, not a regression
-- introduced by the P0-P2 rework.
-- ============================================================================


-- ── 0. Pre-flight — abort rather than half-apply ─────────────────────────────
-- Section 2 promotes idx_items_ref into a real constraint. That cannot succeed
-- with duplicates present, and failing here gives a readable reason instead of
-- an index build error. Checked immediately before applying, not hours before:
-- rows may have been posted since this file was written.

DO $$
DECLARE
  v_dupes bigint;
  v_nulls bigint;
BEGIN
  SELECT count(*) INTO v_dupes
  FROM (SELECT ref FROM public.items GROUP BY ref HAVING count(*) > 1) d;

  SELECT count(*) INTO v_nulls FROM public.items WHERE ref IS NULL;

  IF v_dupes > 0 THEN
    RAISE EXCEPTION 'ABORT: % duplicate ref value(s) present', v_dupes;
  END IF;
  IF v_nulls > 0 THEN
    RAISE EXCEPTION 'ABORT: % row(s) with NULL ref', v_nulls;
  END IF;

  RAISE NOTICE 'pre-flight ok: % rows, no duplicate or null ref',
    (SELECT count(*) FROM public.items);
END $$;


-- ── 1. ref: GENERATED BY DEFAULT -> GENERATED ALWAYS ─────────────────────────
-- BY DEFAULT means a supplied value wins over the sequence. Collision with an
-- existing row was never possible — idx_items_ref rejects it with 23505 — but
-- an *unused* value is accepted and does NOT advance the sequence. nextval then
-- walks toward the squatted number until a legitimate insert collides and
-- fails. ALWAYS removes the client's ability to choose at all.
--
-- Resync first: if a value was already squatted above the sequence position,
-- flipping to ALWAYS alone would leave that landmine in place.

SELECT setval(
  pg_get_serial_sequence('public.items', 'ref'),
  COALESCE((SELECT max(ref) FROM public.items), 0) + 1,
  false
);

ALTER TABLE public.items ALTER COLUMN ref SET GENERATED ALWAYS;


-- ── 2. ref: promote the unique index into a named constraint ─────────────────
-- Uniqueness is ALREADY enforced — migration 009 created idx_items_ref as a
-- unique index, which is why a duplicate ref returns 23505 today. It is an
-- index rather than a constraint, so it does not appear in
-- information_schema.table_constraints, which is what makes it look absent.
--
-- ADD CONSTRAINT ... USING INDEX renames and adopts the existing index instead
-- of building a second identical one. Guarded so a re-run does not fail.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.items'::regclass
      AND contype  = 'u'
      AND conname  = 'items_ref_key'
  ) AND EXISTS (
    SELECT 1 FROM pg_class
    WHERE relname = 'idx_items_ref'
      AND relnamespace = 'public'::regnamespace
  ) THEN
    ALTER TABLE public.items
      ADD CONSTRAINT items_ref_key UNIQUE USING INDEX idx_items_ref;
  END IF;
END $$;


-- ── 3. The stamping trigger ──────────────────────────────────────────────────
-- Identity comes from the caller's JWT, never from the payload.
--
-- The service_role early-return is REQUIRED, not a convenience. /api/admin/items
-- inserts with the service role and legitimately sets user_email, user_name and
-- status (an admin can file an item on a student's behalf, already claimed).
-- Without this branch the admin create flow would silently have its fields
-- rewritten, and auth.jwt() carries no user identity there anyway.
--
-- user_id is deliberately NOT stamped here: items_insert already enforces
-- (select auth.uid()) = user_id via WITH CHECK, so RLS owns that column and two
-- mechanisms fighting over it would be worse than one.
--
-- Built-ins are pg_catalog-qualified to match migration 010's style. Note this
-- is consistency, not necessity: pg_catalog is always implicitly searched first
-- even under search_path = '', which is why claim_item (007, live) calls
-- unqualified now() at its rate-limit step and works.
--
-- The service_role check tries current_user first. auth.role() reads the
-- request.jwt.claims GUC, and that is set by PostgREST — a direct connection,
-- a psql session or a future non-PostgREST server path would leave it null and
-- silently fall through to the authenticated branch. current_user is set by the
-- connection itself and cannot be absent.

CREATE OR REPLACE FUNCTION public.items_stamp_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_claims jsonb;
  v_email  text;
BEGIN
  IF current_user = 'service_role' OR (select auth.role()) = 'service_role' THEN
    RETURN NEW;
  END IF;

  v_claims := (select auth.jwt());
  v_email  := v_claims ->> 'email';

  -- Refuse rather than stamp a null.
  --
  -- claim_item() returns poster_email from this column. A null here does not
  -- fail anything at insert time — it fails weeks later, when a student claims
  -- the item and gets no contact details back, with nothing in any log. That is
  -- the same silent failure this file's header warns about for the unpaired
  -- deploy; it must not be reachable through the trigger either.
  --
  -- A rejected insert is recoverable in the moment. Twenty rows with a null
  -- user_email, discovered in October, are not.
  IF v_email IS NULL THEN
    RAISE EXCEPTION 'items_stamp_insert: no email claim in JWT'
      USING HINT = 'Insert reached the authenticated branch without an email claim. '
                   'Expected only for @estin.dz sessions.';
  END IF;

  NEW.user_email := v_email;

  -- user_name stays nullable on purpose: Google may supply neither full_name
  -- nor name, the column allows null, and a missing display name degrades to
  -- "ESTIN Student" in the UI rather than breaking anything.
  NEW.user_name  := COALESCE(
                      v_claims -> 'user_metadata' ->> 'full_name',
                      v_claims -> 'user_metadata' ->> 'name'
                    );
  NEW.status     := 'open';
  NEW.created_at := pg_catalog.now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS items_stamp_insert ON public.items;

CREATE TRIGGER items_stamp_insert
  BEFORE INSERT ON public.items
  FOR EACH ROW
  EXECUTE FUNCTION public.items_stamp_insert();


-- ── 4. Permissions ───────────────────────────────────────────────────────────
-- Same mechanism migrations 004 and 012 used: a column-level REVOKE has no
-- effect while a table-level grant exists, so the table grant goes first and the
-- insertable columns are re-granted individually.
--
-- Deliberately NOT granted:
--   ref         — GENERATED ALWAYS as of section 1
--   user_email  /  user_name   — stamped from the JWT
--   status      — every transition goes through an RPC (migration 012)
--   created_at  — history; the 90-day expiry reads it
--   id          — has a default and no client sends it
--
-- photo_path is granted: P2-2 writes it from the client on upload.
--
-- anon is revoked and NOT re-granted, and that is a real finding rather than
-- incidental tidying. anon currently holds a table-level INSERT on items:
--
--   postgres  INSERT  |  anon  INSERT  |  authenticated  INSERT  |  service_role  INSERT
--
-- The only thing stopping an unauthenticated insert today is items_insert's
-- WITH CHECK requiring (select auth.role()) = 'authenticated'. That is one
-- policy predicate between the anon key — which ships in the browser bundle —
-- and write access to the board. After this migration anon has no INSERT
-- privilege at all, so the policy is a second line of defence rather than the
-- only one.
--
-- service_role holds its own table-level INSERT grant, independent of
-- authenticated, so revoking from anon and authenticated leaves /api/admin/*
-- working. Verified against production before writing this.

REVOKE INSERT ON public.items FROM anon, authenticated;

GRANT INSERT (
  type,
  category,
  location,
  zone,
  where_left,
  date,
  description,
  photo_url,
  photo_path,
  user_id
) ON public.items TO authenticated;


-- ── 5. Self-test — proves the security property server-side ──────────────────
-- has_column_privilege accounts for table-level and column-level grants
-- together, so a lingering blanket grant cannot fool this.

DO $$
BEGIN
  IF pg_catalog.has_column_privilege('authenticated', 'public.items', 'user_email', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated can still INSERT items.user_email';
  END IF;
  IF pg_catalog.has_column_privilege('authenticated', 'public.items', 'user_name', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated can still INSERT items.user_name';
  END IF;
  IF pg_catalog.has_column_privilege('authenticated', 'public.items', 'status', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated can still INSERT items.status';
  END IF;
  IF pg_catalog.has_column_privilege('authenticated', 'public.items', 'created_at', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated can still INSERT items.created_at';
  END IF;
  IF pg_catalog.has_column_privilege('anon', 'public.items', 'type', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: anon can INSERT into items';
  END IF;

  -- And confirm the grants that SHOULD exist landed, so a typo in the column
  -- list above surfaces here rather than as a broken report form later.
  IF NOT pg_catalog.has_column_privilege('authenticated', 'public.items', 'category', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated lost INSERT on items.category';
  END IF;
  IF NOT pg_catalog.has_column_privilege('authenticated', 'public.items', 'user_id', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated lost INSERT on items.user_id';
  END IF;
  IF NOT pg_catalog.has_column_privilege('authenticated', 'public.items', 'photo_path', 'INSERT') THEN
    RAISE EXCEPTION 'FAIL: authenticated lost INSERT on items.photo_path';
  END IF;

  -- ref must now be system-generated.
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.items'::regclass
      AND attname = 'ref'
      AND attidentity = 'a'          -- 'a' = ALWAYS, 'd' = BY DEFAULT
  ) THEN
    RAISE EXCEPTION 'FAIL: items.ref is not GENERATED ALWAYS';
  END IF;

  RAISE NOTICE 'insert columns locked; identity, status and created_at are server-stamped';
END $$;


-- ── 5b. Is the trigger actually attached? ────────────────────────────────────
-- Pure catalog read. Section 3 could succeed at creating the function and still
-- leave the table untriggered if the CREATE TRIGGER were edited out.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgrelid = 'public.items'::regclass
      AND tgname  = 'items_stamp_insert'
      AND NOT tgisinternal
  ) THEN
    RAISE EXCEPTION 'FAIL: items_stamp_insert is not attached to public.items';
  END IF;
END $$;


-- ── 5c. Behavioural test — fires the trigger, never touches public.items ─────
-- Sections 5 and 5b check grants, column metadata and catalog wiring. None of
-- them executes the trigger body, so a runtime fault in there would ship
-- undetected and surface as a failed student post.
--
-- An earlier draft tested by inserting into public.items and rolling back. That
-- was wrong on three counts, and the reasons are worth keeping:
--
--   * Identity defaults are evaluated while building the tuple, BEFORE the row
--     trigger fires, so a rolled-back insert still consumes a sequence value.
--     Sequences are not transactional. Two test inserts would punch a 2-wide
--     hole in `ref`, which migration 009 went to real trouble to keep gapless.
--   * The compensating setval was not transactional either. Any raise between
--     the inserts and the resync — including through the sentinel path — leaves
--     the gap AND an unresynced sequence.
--   * It made "the test failed" and "the migration failed" the same event, on a
--     production table.
--
-- So the trigger FUNCTION is exercised against a temporary clone instead. LIKE
-- copies columns, NOT NULL and defaults but not foreign keys, so no real user
-- row is needed; the clone gets its own identity sequence, so public.items'
-- sequence is untouched; and the whole thing disappears with the session. The
-- function only ever reads NEW and the JWT — it never names a table — so a
-- clone exercises exactly the same code path.

-- Assertion failures below raise SQLSTATE 'FAIL1', a code no PostgreSQL
-- built-in uses, so 5c(b) can tell its own assertion apart from the trigger's
-- rejection by SQLSTATE rather than by message text. Note P0001 would NOT work
-- for this: it is the default RAISE EXCEPTION code, which is exactly what the
-- trigger's own "no email claim" raise produces, so both sides would match.

DROP TABLE IF EXISTS pg_temp.items_stamp_probe;
CREATE TEMP TABLE items_stamp_probe
  (LIKE public.items INCLUDING DEFAULTS INCLUDING IDENTITY);

CREATE TRIGGER items_stamp_probe_trg
  BEFORE INSERT ON items_stamp_probe
  FOR EACH ROW EXECUTE FUNCTION public.items_stamp_insert();

DO $$
DECLARE
  v_got record;
BEGIN
  -- (a) A hostile payload must be completely overwritten.
  PERFORM set_config('request.jwt.claims', json_build_object(
    'role', 'authenticated',
    'email', 'trigger.test@estin.dz',
    'user_metadata', json_build_object('full_name', 'Trigger Test')
  )::text, true);

  INSERT INTO items_stamp_probe
    (type, category, location, date, user_id, user_email, user_name, status, created_at)
  VALUES
    ('found', 'other', 'library', '2020-01-01', pg_catalog.gen_random_uuid(),
     'attacker@evil.com', 'Attacker', 'claimed', '2000-01-01')
  RETURNING user_email, user_name, status, created_at INTO v_got;

  IF v_got.user_email <> 'trigger.test@estin.dz' THEN
    RAISE EXCEPTION 'FAIL: user_email not stamped (got %)', v_got.user_email
      USING ERRCODE = 'FAIL1';
  END IF;
  IF v_got.user_name <> 'Trigger Test' THEN
    RAISE EXCEPTION 'FAIL: user_name not stamped (got %)', v_got.user_name
      USING ERRCODE = 'FAIL1';
  END IF;
  IF v_got.status::text <> 'open' THEN
    RAISE EXCEPTION 'FAIL: status not forced to open (got %)', v_got.status
      USING ERRCODE = 'FAIL1';
  END IF;
  IF v_got.created_at < pg_catalog.now() - interval '1 minute' THEN
    RAISE EXCEPTION 'FAIL: created_at not stamped (got %)', v_got.created_at
      USING ERRCODE = 'FAIL1';
  END IF;

  -- (b) A session with no email claim must be REFUSED, not stamped null.
  PERFORM set_config('request.jwt.claims',
    json_build_object('role', 'authenticated')::text, true);

  BEGIN
    INSERT INTO items_stamp_probe (type, category, location, date, user_id)
    VALUES ('found', 'other', 'library', '2020-01-01', pg_catalog.gen_random_uuid());
    RAISE EXCEPTION 'FAIL: insert with no email claim was accepted'
      USING ERRCODE = 'FAIL1';
  EXCEPTION
    -- Our own assertion: re-raise, matched by SQLSTATE, never by message text.
    WHEN SQLSTATE 'FAIL1' THEN
      RAISE;
    -- Anything else must be the trigger doing its job.
    WHEN OTHERS THEN
      IF SQLERRM NOT LIKE '%no email claim in JWT%' THEN
        RAISE EXCEPTION 'FAIL: wrong error for missing email claim (% / %)',
          SQLSTATE, SQLERRM USING ERRCODE = 'FAIL1';
      END IF;
  END;

  -- (c) service_role must pass straight through, untouched.
  PERFORM set_config('request.jwt.claims',
    json_build_object('role', 'service_role')::text, true);

  INSERT INTO items_stamp_probe
    (type, category, location, date, user_id, user_email, user_name, status)
  VALUES
    ('found', 'other', 'library', '2020-01-01', pg_catalog.gen_random_uuid(),
     'admin.set@estin.dz', 'Admin Set', 'claimed')
  RETURNING user_email, user_name, status INTO v_got;

  IF v_got.user_email <> 'admin.set@estin.dz'
     OR v_got.user_name <> 'Admin Set'
     OR v_got.status::text <> 'claimed' THEN
    RAISE EXCEPTION 'FAIL: service_role values were rewritten (% / % / %)',
      v_got.user_email, v_got.user_name, v_got.status USING ERRCODE = 'FAIL1';
  END IF;

  PERFORM set_config('request.jwt.claims', '', true);
  RAISE NOTICE 'trigger test passed: hostile values overwritten, null email refused, service_role passed through';
END $$;

DROP TABLE items_stamp_probe;


-- ── 6. Ledger ────────────────────────────────────────────────────────────────

INSERT INTO public.schema_migrations (filename)
VALUES ('013-lock-insert-columns.sql')
ON CONFLICT (filename) DO NOTHING;


-- Verify from a signed-in browser console. The first must fail with 42501, the
-- second must succeed and come back stamped with YOUR email and status 'open':
--
--   await supabase.from('items').insert({
--     type:'found', category:'other', location:'library', date:'2026-08-11',
--     user_id:(await supabase.auth.getUser()).data.user.id,
--     user_email:'someone.else@estin.dz'
--   })                                            -- expect 42501
--
--   await supabase.from('items').insert({
--     type:'found', category:'other', location:'library', date:'2026-08-11',
--     user_id:(await supabase.auth.getUser()).data.user.id
--   })                                            -- expect success
--
--   SELECT ref, user_email, user_name, status, created_at
--   FROM public.items ORDER BY ref DESC LIMIT 1;
--
-- Then delete the test row. And confirm the admin create flow still works —
-- that path runs as service_role and must pass through section 3 untouched.
